### ISSUE TITLE
[Model Weights] The pertained weights model_final.pt file is corrupted

### ISSUE THREAD

**Issue by haaks1998** [tobiassteidle/ML_IDCard_Segmentation_Pytorch#1]
First of all thanks for sharing the model. I tried to test the model with the pre-trained weights provided in the repository but the weights are not unpicking properly. On quick googling, I found that the reason is corrupt weights file... Can you share the pertained weights again (Google Drive link or anything)?? Thanks...

**Comment by tobiassteidle** [comment]
Hi,
please try this download: https://drive.google.com/file/d/1u88se4-G0F-r_ntqm3IblhzMkgxMbzVN/view?usp=sharing

**Comment by haaks1998** [comment]
Thanks..... Solved...
