### ISSUE TITLE
Get assert when testing on my image, what does it mean?

### ISSUE THREAD

**Issue by AndreyStille** [tobiassteidle/ML_IDCard_Segmentation_Pytorch#3]
Hi I get
in utils/image.py
if (len(screenCnt) == 4):
     screenCntList.append(screenCnt)
assert len(screenCntList) == 1
Please help me understand, what does it mean? 
p.s. Thanks for your project

**Comment by tobiassteidle** [comment]
Hi,
please excuse my late reply.

Basically, in these lines, each contour (object) that is found is checked to see if it has 4 corners.
If it does, the 4 corners are stored together in an array.
This happens in:
```
if (len(screenCnt) == 4):
	screenCntList.append(screenCnt)
```

In this case it is assumed that there is only one "rectangle" on the image.
Therefore the check by `assert len(screenCntList) == 1` whether it is really only one object.

I.e. screenCntList is to be seen basically as a multidimensional array in which the first dimension represents the object or the contour and in the second dimension the four corners.

Of course the whole thing is implemented only very rudimentary with a lot of optimism ;-)

**Comment by AndreyStille** [comment]
> 

Thanks for answer
