### ISSUE TITLE
How to train with my dataset?

### ISSUE THREAD

**Issue by TuTinh** [tobiassteidle/ML_IDCard_Segmentation_Pytorch#4]
Please guide me on how to custom my dataset with your proj.

**Comment by tobiassteidle** [comment]
Sorry for the late reply.
Is the topic still relevant for you?

**Comment by gubertu** [comment]
+1

**Comment by tobiassteidle** [comment]
Basically, you can use your own dataset relatively simple.

Each dataset consists of 2 images:
- Image with the id card
- Ground Through image of the corresponding id card

The datasets must be splitted into training, validation and a test sets.
How the datasets are splitted is up to you.
e.g. 60% train, 20% val, 20% test

Create the folder structure like in my example zip.
You can download it here.
https://drive.google.com/file/d/1-Dh7C40LSqdR6e5F2yRiDnm2bXzxwyJ6/view?usp=sharing

Place the ./dataset directory directly in the root directory of the project.
After that, start the training as described in the README.
